USE MOVIE_STREAM;

SELECT MOVIE.Title, COUNT(StreamId) AS N FROM MOVIE NATURAL JOIN STREAM NATURAL JOIN CUSTOMER 
JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name) JOIN REGION USING(RegionId) WHERE REGION.Name = 'Asia'
GROUP BY MOVIE.Title ORDER BY N DESC, MOVIE.Title LIMIT 20;

