USE MOVIE_STREAM;

DELETE FROM MOVIE_ACTOR WHERE MovieId IN(SELECT MovieId FROM MOVIE NATURAL JOIN MOVIE_GENRE NATURAL JOIN GENRE WHERE Label = 'Action')
AND MovieId NOT IN(SELECT MovieId FROM STREAM);