USE MOVIE_STREAM;

DROP VIEW IF EXISTS STREAM_COUNT_BY_COUNTRY;
CREATE VIEW STREAM_COUNT_BY_COUNTRY(Country, StreamCount)
AS(
    SELECT COUNTRY.NAME, COUNT(STREAM.STREAMID) AS N
    FROM CUSTOMER 
        JOIN COUNTRY ON(CUSTOMER.COUNTRY = COUNTRY.NAME)
        LEFT OUTER JOIN STREAM ON(CUSTOMER.CUSTOMERID = STREAM.CUSTOMERID)
    GROUP BY COUNTRY.NAME);