USE MOVIE_STREAM;

SELECT Title, Name FROM ACTOR NATURAL JOIN MOVIE_ACTOR NATURAL JOIN MOVIE 
WHERE MovieId IN (SELECT MovieId FROM ACTOR NATURAL JOIN MOVIE_ACTOR WHERE Name = "Johnny Depp") AND Name <> "Johnny Depp" 
ORDER BY TITLE, Name;