USE MOVIE_STREAM;

SELECT Title, REGION.Name, COUNT(StreamId) FROM MOVIE JOIN (REGION JOIN COUNTRY USING (RegionId) JOIN CUSTOMER ON (COUNTRY.Name = CUSTOMER.Country)) 
LEFT OUTER JOIN STREAM USING (MovieId, CustomerId) 
WHERE Title LIKE "%war%" GROUP BY Title, REGION.Name 
ORDER BY Title, REGION.Name;