USE MOVIE_STREAM;

SELECT COUNTRY.Name, MOVIE.Label, COUNT(StreamId) FROM MOVIE 
NATURAL JOIN STREAM NATURAL JOIN CUSTOMER JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name)
NATURAL JOIN REGION Where REGION.Name = 'Other Countries' GROUP BY MOVIE.Label
ORDER BY COUNTRY.Name, MOVIE.Label;