USE MOVIE_STREAM;

SELECT A1.Name, A2.Name, (COUNT(M1.MovieId)+COUNT(M2.MovieId)) AS N1,  FROM (MOVIE_ACTOR M1 NATURAL JOIN ACTOR A1) 
JOIN (MOVIE_ACTOR M2 NATURAL JOIN ACTOR A2) USING (MovieId) WHERE A1.Name < A2.Name AND M1.MovieId <> M2.MovieId GROUP BY A1.Name, A2.Name
HAVING N2>=40;

SELECT DISTINCT ACTOR.Name FROM MOVIE_ACTOR NATURAL JOIN ACTOR WHERE MovieId IN(SELECT MovieId FROM MOVIE_ACTOR)
