USE MOVIE_STREAM;

DELETE FROM STREAM WHERE MovieId IN (SELECT MovieId FROM MOVIE NATURAL JOIN MOVIE_GENRE NATURAL JOIN GENRE WHERE Label = "Biography" 
AND Duration <= 120) AND CustomerId IN (SELECT CustomerId FROM CUSTOMER JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name) JOIN REGION USING(RegionId) 
WHERE REGION.Name <> "America");