USE MOVIE_STREAM;

SELECT A1.Name, A2.Name,  COUNT(*) AS N FROM (MOVIE_ACTOR M1 NATURAL JOIN ACTOR A1) JOIN (MOVIE_ACTOR M2 NATURAL JOIN ACTOR A2) 
USING (MovieId) WHERE A1.Name < A2.Name GROUP BY A1.Name, A2.Name HAVING N >= 4 ORDER BY N DESC, A1.Name, A2.Name;
