USE MOVIE_STREAM;

UPDATE STREAM SET Charge = 0 WHERE CustomerId NOT IN(SELECT CustomerId FROM CUSTOMER WHERE Country = 'America')
AND MovieId IN(SELECT MovieId FROM MOVIE NATURAL JOIN MOVIE_GENRE NATURAL JOIN GENRE WHERE Duration <= 120 AND Label = 'Biography');