USE MOVIE_STREAM;

SELECT StreamDate, Title, Name, Country FROM STREAM JOIN MOVIE USING(MovieId) JOIN CUSTOMER USING (CustomerId) 
WHERE MovieId IN (SELECT MovieId FROM ACTOR NATURAL JOIN MOVIE_ACTOR WHERE Name = "Johnny Depp") 
AND MovieId NOT IN (SELECT MovieId FROM ACTOR NATURAL JOIN MOVIE_ACTOR WHERE Name = "Helena Bonham Carter") 
AND Country <> "China"  
ORDER BY StreamDate DESC LIMIT 15;