USE MOVIE_STREAM;

UPDATE STREAM SET Charge = Charge+1.5 WHERE MovieId IN(SELECT MovieId FROM MOVIE WHERE Duration >= 180) 
AND CustomerId IN(SELECT CustomerId FROM CUSTOMER NATURAL JOIN COUNTRY NATURAL JOIN REGION WHERE REGION.Name = 'Europe');